---

- name: Set default system language
  become: yes
  when: base_locale is defined
  shell: locale-gen "{{ base_locale }}"

- name: set timezone to "{{ base_timezone }}"
  become: yes
  when: base_timezone is defined
  community.general.timezone:
    name: "{{ base_timezone }}"

- name: Set the hostname
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Build hosts file"
  become: yes
  when: hostvars[inventory_hostname]['ansible_host'] is defined
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  loop: "{{ ansible_play_hosts }}"

- name: Ssh config strict hostkey
  become: yes
  lineinfile: dest=/etc/ssh/ssh_config line='StrictHostKeyChecking no'

- name: Ssh config userknown
  become: yes
  lineinfile: dest=/etc/ssh/ssh_config line='UserKnownHostsFile /dev/null'

- name: Ensure low swappiness value
  become: yes
  sysctl:
    name: vm.swappiness
    value: '5'
    state: present

- name: Playbooks touch files folder
  file:
    path: ~/.playbooks
    owner: "{{ ansible_user }}"
    state: directory
    mode: 0755
