---

- name: Ensure admin group is present
  become: yes
  group:
    name: admin
    state: present

- name: Ansible user properties
  become: yes
  user:
    append: yes
    name: "{{ ansible_user }}"
    shell: /bin/bash
    groups:
      - admin

- name: No passwd for admin group on sudo
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%ADMIN ALL='
    line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
 
- name: Unlock ansible account and disable password auth
  become: yes
  shell: usermod -p '*' {{ ansible_user }}
