---

- name: Execute openstack-ansible setup-hosts
  become: true
  run_once: true
  ansible.builtin.command: openstack-ansible --ssh-extra-args="{{ os_install_ssh_args }}" setup-hosts.yml
  args:
    creates: "{{ os_install_firstboot_creates_path }}"
    chdir: /opt/openstack-ansible/playbooks

- name: Execute openstack-ansible setup-infra
  become: true
  run_once: true
  ansible.builtin.command: openstack-ansible --ssh-extra-args="{{ os_install_ssh_args }}" setup-infrastructure.yml
  args:
    creates: "{{ os_install_firstboot_creates_path }}"
    chdir: /opt/openstack-ansible/playbooks

- name: Execute openstack-ansible setup-openstack
  become: true
  run_once: true
  ansible.builtin.command: openstack-ansible --ssh-extra-args="{{ os_install_ssh_args }}" setup-openstack.yml
  args:
    creates: "{{ os_install_firstboot_creates_path }}"
    chdir: /opt/openstack-ansible/playbooks

...
