---

- name: Swap off
  shell: |
    swapoff -a
    sed -i 's/^.*swap.*$/#/g' /etc/fstab
  become: yes

- name: create lxc disk
  shell: |
    disk="/dev/vda"
    partition="${disk}1"
    if [[ -e /dev/vdb ]]; then
      disk="/dev/vdb"
      partition="${disk}1"
    fi
    if [[ -e /dev/sdb ]]; then
      disk="/dev/sdb"
      partition="${disk}1"
    fi
    if [[ -e /dev/nvme0 ]]; then
      disk="/dev/nvme0n1"
      partition="${disk}p1"
    fi
    yes Yes | parted -a optimal $disk mklabel msdos
    parted -a optimal $disk mkpart primary ext4 0% 100%
    sleep 5
    mkfs.ext4 ${partition}
    mkdir -p /var/lib/lxc
    mount ${partition} /var/lib/lxc
    echo `blkid "${partition}" | awk '{print$2}' | sed -e 's/"//g'` /var/lib/lxc   ext4   noatime,nobarrier   0   0 >> /etc/fstab
  args:
    executable: /bin/bash
  become: yes

- name: Override openssl.cnf (add altsubjectname line)
  template:
    src: templates/openssl.cnf.j2
    dest: /etc/ssl/openssl.cnf
  become: yes

- name: Ip forwarding
  shell: |
    echo 1 > /proc/sys/net/ipv4/ip_forward
    sed -i "s;#net.ipv4.ip_forward=1;net.ipv4.ip_forward=1;" /etc/sysctl.conf
  become: yes

- name: Prepare haproxy install folder
  file:
    path: /opt/cache/files/v0.8.0
    state: directory
    owner: root
    group: root
    mode: 0775
  become: yes

- name: prepare ethtobr script
  shell: touch /usr/local/bin/ethtobr.sh
  become: yes

- name: br-vlan script setting fix
  blockinfile:
    path: /usr/local/bin/ethtobr.sh
    block: |
      #!/bin/bash
      ip a del 192.168.85.70/25 dev eth2
      route del -net 192.168.85.0/25 dev eth2
      route add -net 192.168.85.0/25 dev br-vlan
      ip a add 192.168.90.1/24 dev br-vlan
  become: yes

- name: Ensure br-vlan and eth2 are well defined
  cron:
    name: fix-brvlan
    user: root
    job: /bin/bash /usr/local/bin/ethtobr.sh
  become: yes

- name: Interface oscontroller
  blockinfile:
    path: /etc/network/interfaces
    block: |
      # Container/Host management VLAN interface
      auto eth1.10
      iface eth1.10 inet manual
          vlan-raw-device eth1

      # OpenStack Networking VXLAN (tunnel/overlay) VLAN interface
      auto eth2.30
      iface eth2.30 inet manual
          vlan-raw-device eth2

      # OpenStack Networking VLAN interface for storage
      auto eth1.20
      iface eth1.20 inet manual
          vlan-raw-device eth1

      # OpenStack Networking VLAN bridge
      auto br-vlan
      iface br-vlan inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth2
          address 192.168.85.70
          netmask 255.255.255.128
          pre-up ip a del 192.168.85.70/25 dev eth2
          #post-up ip a del 192.168.85.70/25 dev eth2
          post-up ethtool -K eth2 gro off
          post-up ip a add 192.168.90.1/24 dev br-vlan
          post-up iptables -t nat -A POSTROUTING -s 192.168.90.0/24 ! -d 192.168.90.0/24 -j MASQUERADE


      # Container/Host management bridge
      auto br-mgmt
      iface br-mgmt inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth1.10
          address 172.29.236.101
          netmask 255.255.252.0
          dns-nameservers 8.8.8.8 8.8.4.4
          # gateway 172.29.236.1
          up sed -i "s/^.*DNS=.*$/DNS=8.8.8.8/;s/^.*FallbackDNS=.*$/FallbackDNS=8.8.4.4/" /etc/systemd/resolved.conf
          post-up ip addr add 172.29.236.1/22 dev br-mgmt
          #post-up iptables -t nat -A POSTROUTING -o br-mgmt -j MASQUERADE
          #post-up iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
          #post-up iptables -t nat -A POSTROUTING -s 172.29.236.0/22 -j MASQUERADE
          #post-up iptables -t nat -A POSTROUTING -s 172.29.236.0/22 ! -d 172.29.236.0/22 -j MASQUERADE
          post-up service systemd-resolved restart

      # Bind the External VIP
      auto br-mgmt:0
      iface br-mgmt:0 inet static
          address 172.29.236.100
          netmask 255.255.252.0

      auto br-vxlan
      iface br-vxlan inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth2.30
          address 172.29.248.10
          netmask 255.255.252.0

      auto br-storage
      iface br-storage inet manual
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth1.20
  become: yes

- name: Reboot
  shell: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  become: yes

- name: Ensure oscontroller is up
  pause:
    minutes: 5
