---

- name: Create a new primary partition
  become: yes
  parted:
    device: "{{ disk_device }}"
    number: 1
    state: present

- name: Create an ext4 filesystem
  become: yes
  filesystem:
    fstype: "{{ disk_type }}"
    dev: "{{ disk_partition }}"

- name: Mount and bind a volume
  become: yes
  mount:
    path: "{{ disk_mount_path }}" 
    src: "{{ disk_partition }}"
    opts: noatime,nobarrier
    state: mounted
    fstype: "{{ disk_type }}"

