---

- name: Logs folder
  become: yes
  file:
    path: "{{ os_preinstall_logs_folder }}"
    owner: "{{ ansible_user }}"
    state: directory
    mode: 0775

- name: Copy local vagrant private key file to osinstaller
  become: yes
  copy:
    src: ~/.vagrant.d/insecure_private_key
    dest: ~/.ssh/id_rsa
    mode: 0600

- name: clone openstack-ansible repo
  become: yes
  git:
    repo: "{{ os_preinstall_osa_repository }}"
    version: "{{ os_preinstall_osa_version }}"
    dest: /opt/openstack-ansible

- name: bootstrap the openstack-ansible project
  become: yes
  shell: |
    ./scripts/./bootstrap-ansible.sh >{{ os_preinstall_logs_folder }}/log_osa_bootstrap_$(date +%s) 2>&1
    rsync -av etc/openstack_deploy /etc/
  args:
    executable: /bin/bash
    chdir: /opt/openstack-ansible
    creates: "{{ os_preinstall_firstboot_creates_path }}"

- name: python3-yaml library
  become: yes
  apt:
    name: python3-yaml
    state: present

- name: Default secrets
  become: yes
  shell: |
    python3 pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml
  args:
    chdir: /opt/openstack-ansible/scripts
    creates: "{{ os_preinstall_firstboot_creates_path }}"

- name: Override horizon admin password
  become: yes
  lineinfile:
    path: /etc/openstack_deploy/user_secrets.yml
    regexp: '^keystone_auth_admin_password:'
    line: "keystone_auth_admin_password: {{ os_preinstall_admin_password }}"

- name: openstack_user_config.yml file
  become: yes
  template:
    src: templates/openstack_user_config.yml.j2
    dest: /etc/openstack_deploy/openstack_user_config.yml
    mode: 644

- name: user_variables.yml file
  become: yes
  template:
    src: templates/user_variables.yml.j2
    dest: /etc/openstack_deploy/user_variables.yml
    mode: 644

- name: "Ensure infra nodes are resolved into hosts file"
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "{{ os_preinstall_mgmt_network }}.{{ item.suffix }} {{ item.name }}"
    state: present
  loop: "{{ os_preinstall_infra_nodes }}" 


