---

- name: Root .ssh folder
  become: true
  ansible.builtin.file:
    path: ~/.ssh
    owner: root
    state: directory
    mode: '0700'

- name: Prepare ssh authorized key file onto target hosts
  become: true
  ansible.builtin.copy:
    src: .ssh/authorized_keys
    dest: ~/.ssh/authorized_keys
    remote_src: true
    mode: '0600'

...
