---

- name: Root .ssh folder
  file:
    path: ~/.ssh
    owner: root
    state: directory
    mode: 0700
  become: yes

- name: Prepare ssh authorized key file onto target hosts
  copy:
    src: .ssh/authorized_keys
    dest: ~/.ssh/authorized_keys
    remote_src: yes
    mode: 0600
  become: yes

