- hosts: all
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Prerequisites
      shell: >
        apt-get update -y --force-yes;
        apt-get dist-upgrade -y --force-yes;
        apt-get install -y --force-yes bridge-utils debootstrap ifenslave ifenslave-2.6 lsof lvm2 ntp ntpdate openssh-server sudo tcpdump vlan;
        echo 'bonding' >> /etc/modules;
        echo '8021q' >> /etc/modules;
        service ntp restart;
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Set authorized key took from file
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  pre_tasks:
    - name: Local prerequisites
      local_action: shell DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes aptitude git ntp ntpdate openssh-server python-dev build-essential
      run_once: true
    - local_action: shell ip a | grep {{ vlan_dev }}.10 || sudo vconfig add {{ vlan_dev }} 10
      run_once: true
    - local_action: shell ip link set up {{ vlan_dev }}.10
      run_once: true
    - local_action: shell ip a | grep 172.29.236.41 || sudo ip addr add 172.29.236.41 dev {{ vlan_dev }}.10
      run_once: true
    - local_action: shell route -n | grep 172.29.236.0 || sudo route add -net 172.29.236.0/22 dev {{ vlan_dev }}.10
      run_once: true

- hosts: oscontroller
  become: yes
  tasks:
    - name: Interface oscontroller
      blockinfile:
        path: /etc/network/interfaces
        block: |
          # Container/Host management VLAN interface
          auto eth1.10
          iface eth1.10 inet manual
              vlan-raw-device eth1

          # OpenStack Networking VXLAN (tunnel/overlay) VLAN interface
          auto eth2.30
          iface eth2.30 inet manual
              vlan-raw-device eth2

          # Container/Host management bridge
          auto br-mgmt
          iface br-mgmt inet static
              bridge_stp off
              bridge_waitport 0
              bridge_fd 0
              bridge_ports eth1.10
              address 172.29.236.11
              netmask 255.255.252.0
              gateway 172.29.236.1
              dns-nameservers 8.8.8.8 8.8.4.4

          # Bind the External VIP
          auto br-mgmt:0
          iface br-mgmt:0 inet static
              address 172.29.236.10
              netmask 255.255.252.0

          # OpenStack Networking VXLAN (tunnel/overlay) bridge
          #
          # Only the COMPUTE and NETWORK nodes must have an IP address
          # on this bridge. When used by infrastructure nodes, the
          # IP addresses are assigned to containers which use this
          # bridge.
          #
          auto br-vxlan
          iface br-vxlan inet manual
              bridge_stp off
              bridge_waitport 0
              bridge_fd 0
              bridge_ports eth2.30

          # OpenStack Networking VLAN bridge
          auto br-vlan
          iface br-vlan inet manual
              bridge_stp off
              bridge_waitport 0
              bridge_fd 0
              bridge_ports eth2

    - name: Reboot
      shell: /sbin/shutdown -r +1 
      async: 0
      poll: 0
      ignore_errors: true

- hosts: oscompute1
  become: yes
  tasks:
    - name: Interface oscontroller
      blockinfile:
        path: /etc/network/interfaces
        block: |
          # Container/Host management VLAN interface
          auto eth1.10
          iface eth1.10 inet static 
              vlan-raw-device eth1
              
          #address 172.29.236.12
          #netmask 255.255.252.0

          # Container/Host management bridge
          auto br-mgmt
          iface br-mgmt inet static
              bridge_stp off
              bridge_waitport 0
              bridge_fd 0
              bridge_ports eth1.10
              address 172.29.236.12
              netmask 255.255.252.0
              #gateway 172.29.236.1
              dns-nameservers 8.8.8.8 8.8.4.4

          # OpenStack Networking VXLAN (tunnel/overlay) VLAN interface
          auto eth2.30
          iface eth2.30 inet manual
              vlan-raw-device eth2

          # OpenStack Networking VXLAN (tunnel/overlay) bridge
          #
          # Only the COMPUTE and NETWORK nodes must have an IP address
          # on this bridge. When used by infrastructure nodes, the
          # IP addresses are assigned to containers which use this
          # bridge.
          #
          # compute1 VXLAN (tunnel/overlay) bridge config
          auto br-vxlan
          iface br-vxlan inet static
              bridge_stp off
              bridge_waitport 0
              bridge_fd 0
              bridge_ports eth2.30
              address 172.29.240.12
              netmask 255.255.252.0

          # OpenStack Networking VLAN bridge
          auto br-vlan
          iface br-vlan inet manual
              bridge_stp off
              bridge_waitport 0
              bridge_fd 0

    - name: Reboot
      shell: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true

- hosts: oscompute2
  become: yes
  tasks:
    - name: Interface oscontroller
      blockinfile:
        path: /etc/network/interfaces
        block: |
          # Container/Host management VLAN interface
          auto eth1.10
          iface eth1.10 inet static 
              vlan-raw-device eth1
          
          #address 172.29.236.13
          #netmask 255.255.252.0
          
          # Container/Host management bridge
          auto br-mgmt
          iface br-mgmt inet static
              bridge_stp off
              bridge_waitport 0
              bridge_fd 0
              bridge_ports eth1.10
              address 172.29.236.13
              netmask 255.255.252.0
              #gateway 172.29.236.1
              dns-nameservers 8.8.8.8 8.8.4.4

          # OpenStack Networking VXLAN (tunnel/overlay) VLAN interface
          auto eth2.30
          iface eth2.30 inet manual
              vlan-raw-device eth2

          # OpenStack Networking VXLAN (tunnel/overlay) bridge
          #
          # Only the COMPUTE and NETWORK nodes must have an IP address
          # on this bridge. When used by infrastructure nodes, the
          # IP addresses are assigned to containers which use this
          # bridge.
          #
          # compute1 VXLAN (tunnel/overlay) bridge config
          auto br-vxlan
          iface br-vxlan inet static
              bridge_stp off
              bridge_waitport 0
              bridge_fd 0
              bridge_ports eth2.30
              address 172.29.240.13
              netmask 255.255.252.0
          
          # OpenStack Networking VLAN bridge
          auto br-vlan
          iface br-vlan inet manual
              bridge_stp off
              bridge_waitport 0
              bridge_fd 0

    - name: Reboot
      shell: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true

