---

- name: Swap off
  shell: |
    swapoff -a
    sed -i 's/^.*swap.*$/#/g' /etc/fstab
  become: yes

- name: create cinder lvm
  shell: |
    disk="vda"
    [[ -e /dev/vdb ]] && disk="vdb"
    [[ -e /dev/sdb ]] && disk="sdb"
    pvcreate /dev/${disk}
    vgcreate cinder-volumes /dev/${disk}
    sed -i "s;# filter = .*/dev/cdrom.*$;filter = [ \"a/sda1/\", \"a/${disk}/\", \"r|.*/|\" ];" /etc/lvm/lvm.conf
  args:
    executable: /bin/bash
  become: yes

- name: Interface osstorage
  blockinfile:
    path: /etc/network/interfaces
    block: |
      # Container/Host management VLAN interface
      auto eth1.10
      iface eth1.10 inet static
          vlan-raw-device eth1

      # OpenStack Networking VXLAN (tunnel/overlay) VLAN interface
      auto eth2.30
      iface eth2.30 inet manual
          vlan-raw-device eth2

      # OpenStack Networking VLAN interface for storage
      auto eth1.20
      iface eth1.20 inet manual
          vlan-raw-device eth1

      # Container/Host management bridge
      auto br-mgmt
      iface br-mgmt inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth1.10
          address 172.29.236.131
          netmask 255.255.252.0
          #gateway 172.29.236.1
          dns-nameservers 8.8.8.8 8.8.4.4
          up sed -i "s/#DNS=/DNS=8.8.8.8/;s/#FallbackDNS=/FallbackDNS=8.8.4.4/" /etc/systemd/resolved.conf
          #post-up route del default dev eth0
          post-up service systemd-resolved restart
          #post-up route add -net 172.29.236.0/22 gw 172.29.236.1 dev br-mgmt

      auto br-vxlan
      iface br-vxlan inet manual
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth2.30

      # OpenStack Networking VLAN bridge
      auto br-vlan
      iface br-vlan inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth2
          address 192.168.85.80
          netmask 255.255.255.128
          pre-up ip a del 192.168.85.80/25 dev eth2
          post-up ethtool -K eth2 gro off

      # compute1 Storage bridge
      auto br-storage
      iface br-storage inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth1.20
          address 172.29.244.120
          netmask 255.255.252.0
  become: yes

- name: Reboot
  shell: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  become: yes

- name: Ensure osstorage is up
  pause:
    minutes: 5
