---

- name: Swap off
  become: true
  ansible.builtin.command: "{{ item }}"
  args:
    creates: "{{ swapoff_firstboot_creates_path }}"
  loop:
    - swapoff -a
    - sed -i 's/^.*swap.*$/#/g' /etc/fstab

...
