---

- name: Swap off
  shell: |
    swapoff -a
    sed -i 's/^.*swap.*$/#/g' /etc/fstab
  become: yes

- name: create libvirt disk
  shell: |
    disk="/dev/vda"
    partition="${disk}1"
    if [[ -e /dev/vdb ]]; then
      disk="/dev/vdb"
      partition="${disk}1"
    fi
    if [[ -e /dev/sdb ]]; then
      disk="/dev/sdb"
      partition="${disk}1"
    fi
    if [[ -e /dev/nvme0 ]]; then
      disk="/dev/nvme0n1"
      partition="${disk}p1"
    fi
    yes Yes | parted -a optimal $disk mklabel msdos
    parted -a optimal $disk mkpart primary ext4 0% 100%
    sleep 5
    mkfs.ext4 ${partition}
    mkdir -p /var/lib/nova
    mount "${partition}" /var/lib/nova
    echo `blkid "${partition}" | awk '{print$2}' | sed -e 's/"//g'` /var/lib/nova   ext4   noatime,nobarrier   0   0 >> /etc/fstab
  args:
    executable: /bin/bash
  become: yes

- name: Interface oscompute2
  blockinfile:
    path: /etc/network/interfaces
    block: |
      # Container/Host management VLAN interface
      auto eth1.10
      iface eth1.10 inet manual
          vlan-raw-device eth1

      # OpenStack Networking VXLAN (tunnel/overlay) VLAN interface
      auto eth2.30
      iface eth2.30 inet manual
          vlan-raw-device eth2

      auto eth2.40
      iface eth2.40 inet manual
          vlan-raw-device eth2

      # OpenStack Networking VLAN interface for storage
      auto eth1.20
      iface eth1.20 inet manual
          vlan-raw-device eth1

      # Container/Host management bridge
      auto br-mgmt
      iface br-mgmt inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth1.10
          address 172.29.236.121/22

      # OpenStack Networking VLAN bridge
      auto br-vlan
      iface br-vlan inet manual
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth2.40
          post-up ethtool -K eth2 gro off

      # compute1 VXLAN (tunnel/overlay) bridge config
      auto br-vxlan
      iface br-vxlan inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth2.30
          address 172.29.248.6/22

      # compute1 Storage bridge
      auto br-storage
      iface br-storage inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth1.20
          address 172.29.244.113/22
  become: yes

- name: Reboot
  shell: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  become: yes

- name: Ensure compute node is up
  pause:
    minutes: 2

