---

- name: Set openssl config for infra node
  hosts: infras
  serial: 1
  strategy: linear
  roles:
    - role: ssl_altname
      tags: [prerequisites, ssl_altname]

- name: Ensure prerequisites for openstack install
  hosts: all
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: base
      tags: [prerequisites, base]
    - role: ntp
      tags: [prerequisites, base]
    - role: osa_sshkeys
      tags: [prerequisites, osa_sshkeys]
    - role: swapoff
      tags: [prerequisites, swap]
    - role: sysctl
      tags: [prerequisites, sysctl]
    - role: network_config
      tags: [prerequisites, network]

- name: Prepare additional disk for infra and computes nodes
  hosts:
    - infras
    - computes
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: disk
      tags: [prerequisites, disk]

- name: Prepare lvm partition for cinder needs
  hosts:
    - storages
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: lvm
      tags: [prerequisites, lvm]

- name: Set end state for computes and storages nodes
  hosts:
    - computes
    - storages
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: end
      tags: [prerequisites]

- name: Install openstack
  hosts: installer
  serial: 1
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: os_preinstall
      tags: [os, os_preinstall]
    - role: os_install
      tags: [os, os_install]

- name: Make openstack fine-tuning settings via API
  hosts: infras
  serial: 1
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: os_postinstall
      tags: [os, postinstall, os_postinstall]
    - role: end
      tags: [postinstall]

- name: Deploy k8s if option is setted
  hosts: installer
  serial: 1
  strategy: linear
  vars_files:
    - sizing_vars.yml
  roles:
    - role: k8s_deploy
      tags: [postinstall, k8s_deploy]
      when: global_k8s_deploy == "1"
    - role: end
      tags: [postinstall]
      when: global_k8s_deploy == "1"

...
