---

- name: Swap off
  shell: |
    swapoff -a
    sed -i 's/^.*swap.*$/#/g' /etc/fstab
  become: yes

- name: Interface osinstaller
  blockinfile:
    path: /etc/network/interfaces
    block: |
      # Container/Host management VLAN interface
      auto eth1.10
      iface eth1.10 inet manual
          vlan-raw-device eth1

      # OpenStack Networking VLAN bridge
      auto br-vlan
      iface br-vlan inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth2
          address 192.168.85.20
          netmask 255.255.255.128
          pre-up ip a del 192.168.85.20/25 dev eth2
          post-up ethtool -K eth2 gro off
          post-up ip a add 192.168.90.2/24 dev br-vlan

      # Container/Host management bridge
      auto br-mgmt
      iface br-mgmt inet static
          bridge_stp off
          bridge_waitport 0
          bridge_fd 0
          bridge_ports eth1.10
          address 172.29.236.41
          netmask 255.255.252.0
          dns-nameservers 8.8.8.8 8.8.4.4
          up sed -i "s/^.*DNS=.*$/DNS=8.8.8.8/;s/^.*FallbackDNS=.*$/FallbackDNS=8.8.4.4/" /etc/systemd/resolved.conf
          post-up service systemd-resolved restart
  become: yes

- name: Reboot
  shell: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  become: yes

- name: Ensure installer is up
  pause:
    minutes: 5

- name: Copy local vagrant private key file to osinstaller
  copy:
    src: ~/.vagrant.d/insecure_private_key
    dest: ~/.ssh/id_rsa
    mode: 0600
  become: yes

- name: Generate local vagrant public key file
  shell: cp /home/vagrant/.ssh/authorized_keys ~/.ssh/id_rsa.pub && chmod 0644 ~/.ssh/id_rsa.pub
  become: yes

- name: clone openstack-ansible (stein release) repo
  shell: |
    git clone -b stable/stein https://git.openstack.org/openstack/openstack-ansible
  args:
    chdir: /opt
  become: yes

- name: bootstrap the osa project
  shell: |
    ./scripts/./bootstrap-ansible.sh >/tmp/logbootstrap 2>&1
    rsync -av etc/openstack_deploy /etc/
  args:
    chdir: /opt/openstack-ansible
  become: yes

- name: python-yaml library
  apt:
    name: python-yaml
    state: present
  become: yes

- name: Default secrets
  shell: |
    python pw-token-gen.py --file /etc/openstack_deploy/user_secrets.yml
  args:
    chdir: /opt/openstack-ansible/scripts
  become: yes

- name: Override horizon admin password
  shell: |
    sed -i "s/keystone_auth_admin_password: .*$/keystone_auth_admin_password: toor/" /etc/openstack_deploy/user_secrets.yml
  become: yes

- name: sync assets folder
  synchronize:
    src: assets/
    dest: assets/
  become: yes

- name: Override settings
  shell: |
    [[ -f openstack_user_config.yml ]] || cp -f openstack_user_config.yml.dist openstack_user_config.yml
    [[ -f user_variables.yml ]] || cp -f user_variables.yml.dist user_variables.yml
    [[ -f openstack_user_config.yml ]] && cp openstack_user_config.yml /etc/openstack_deploy/
    [[ -f user_variables.yml ]] && cp user_variables.yml /etc/openstack_deploy/
    [[ -d env.d ]] && rsync -av env.d/ /etc/openstack_deploy/env.d/
    sed -i "s/nova_virt_type:.*/nova_virt_type: {{ libvirt_driver }}/" /etc/openstack_deploy/user_variables.yml
  args:
    chdir: assets
    executable: /bin/bash
  become: yes

- name: Override settings, step 2
  shell: |
    [[ -f openstack_user_config.yml ]] || mv openstack_user_config.yml.test.example openstack_user_config.yml
    [[ -f user_variables.yml ]] || cp user_variables.yml.test.example user_variables.yml
  args:
    chdir: /etc/openstack_deploy
    executable: /bin/bash
  become: yes

- name: "Ensure infra1 is resolved into hosts file"
  lineinfile:
    dest: /etc/hosts
    line: "172.29.236.101 infra1"
    state: present
  with_items: "{{ ansible_play_hosts }}"
  when: hostvars[inventory_hostname]['ansible_host'] is defined
  become: yes

- name: Execute openstack-ansible setup-hosts
  shell: |
    openstack-ansible --ssh-extra-args="-C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=30 -o ConnectionAttempts=5" setup-hosts.yml >/tmp/loghosts 2>&1
  args:
    chdir: /opt/openstack-ansible/playbooks
  become: yes

- name: Pause after setup hosts
  pause:
    minutes: 1

- name: Execute openstack-ansible setup-infra
  shell: |
    openstack-ansible --ssh-extra-args="-C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=30 -o ConnectionAttempts=5" setup-infrastructure.yml >/tmp/loginfra 2>&1
  args:
    chdir: /opt/openstack-ansible/playbooks
  become: yes

- name: Pause after setup infra
  pause:
    minutes: 1

- name: Execute openstack-ansible setup-openstack
  shell: |
    openstack-ansible --ssh-extra-args="-C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=30 -o ConnectionAttempts=5" setup-openstack.yml >/tmp/logos 2>&1
  args:
    executable: /bin/bash
    chdir: /opt/openstack-ansible/playbooks
  become: yes

- name: Pause after setup openstack
  pause:
    minutes: 1
