---

network_config_pkgs:
  - bridge-utils
  - debootstrap
  - ifenslave
  - lsof
  - ntp
  - ntpdate
  - vlan

network_is_openstack_route_needed: false

network_config_block: |
  auto br-vlan
  iface br-vlan inet static
      bridge_stp off
      bridge_waitport 0
      bridge_fd 0
      bridge_ports eth2
      address 192.168.1.2
      netmask 255.255.255.0

...
